### ISSUE TITLE
Add information of repository to README

### ISSUE THREAD

**Issue by edmondchuc** [usc-isi-i2/gaia-visualization#4]
Hi, I am interested in RDF visualization tools. Please add some comments to the README file to express the capability/purpose of this repository.

**Comment by fatestigma** [comment]
Hi edmondchuc, 

This repo is specific for AIDA project. Though I updated README, I don't think this repo is what you want. I'll close this issue, meanwhile you can check out another repo [usc-isi-i2/ontology-visualization](https://github.com/usc-isi-i2/ontology-visualization) which is for more general RDF visualization.

Xi
